[theme]
# The dark "Stone" color for buttons and interactive elements
primaryColor = "#96c31bff"

# The soft "Off White" color for the main background
backgroundColor = "#efeeea"

# The "Light Grey" color for the sidebar and input components
secondaryBackgroundColor = "#d8e7d1"

# The dark "Stone" color for text readability
textColor = "#1a1a17ff"

# Using a clean sans-serif font
font = "sans serif"
